name: moneyboi
description: A new Flutter project.

publish_to: "none"

version: 2.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bot_toast: ^4.0.1
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  expandable: ^5.0.1
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  fl_chart: ^0.55.1
  flutter:
    sdk: flutter
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
  get: ^4.6.1
  google_fonts: ^2.1.0
  hive: ^2.0.4
  intl: ^0.17.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/
