// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo10MtBmvrSoOP0iJa6pDKMyn2CS_bnhE',
    appId: '1:654986056211:web:9aa76b4772133233f5a5e6',
    messagingSenderId: '654986056211',
    projectId: 'moneyboi-c4c20',
    authDomain: 'moneyboi-c4c20.firebaseapp.com',
    databaseURL: 'https://moneyboi-c4c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneyboi-c4c20.appspot.com',
    measurementId: 'G-CXVWJDL5MR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sAvldvhwHQUz1J3g3yxL2mOt945L834',
    appId: '1:654986056211:android:7e1d9a5c0b5e942cf5a5e6',
    messagingSenderId: '654986056211',
    projectId: 'moneyboi-c4c20',
    databaseURL: 'https://moneyboi-c4c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneyboi-c4c20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6j-SG9v0cfXLgCBDpRtUcIuK264zjopM',
    appId: '1:654986056211:ios:ca6d672ed17db7f6f5a5e6',
    messagingSenderId: '654986056211',
    projectId: 'moneyboi-c4c20',
    databaseURL: 'https://moneyboi-c4c20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'moneyboi-c4c20.appspot.com',
    iosClientId: '654986056211-mnc3guhqlsagf0q7ofo3f6h8si8vlpml.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyboi',
  );
}
